version: '3.1'

services:
  postgres:
    container_name: youdude-db-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yoududedb
    ports:
      - "5432:5432"
