version: '3.1'

services:
  postgres:
    image: postgres:12.3-alpine
    container_name: youdude-db-container
    hostname: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youdude
    ports:
      - "5432:5432"
