version: '3.1'

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#    - 8080:8080
#    - 443:443
  youdude:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youdude
    depends_on:
      - postgres
      - youdude-admin
    ports:
      - 8080:8080
    networks:
      - youdude-network
  youdude-auth:
    build:
      context: ./youdude-auth
      dockerfile: Dockerfile-auth
    ports:
      - 8081:8081
    container_name: youdude-auth
    hostname: youdude-auth
    networks:
      - youdude-network
  youdude-admin:
    build:
      context: ./youdude-admin
      dockerfile: Dockerfile-admin
    ports:
      - 8090:8090
    container_name: youdude-admin
    hostname: youdude-admin
    networks:
      - youdude-network
  postgres:
    image: postgres:12.3-alpine
    container_name: youdude-database
    hostname: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youdude
    ports:
      - 5432:5432
    networks:
      - youdude-network
networks:
  youdude-network:
    driver: bridge
